version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    rebase-strategy: 'disabled'
    commit-message:
      prefix: 'feat'
      include: 'scope'
